name: DemoNewCD
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'www.cec.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy dev
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'www.cec.com.br'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy hmg
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'www.cec.com.br'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy prod
  
